# Generated by Django 3.2 on 2021-05-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_member_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
