# Generated by Django 3.2 on 2021-05-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_member_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='add',
            field=models.CharField(default='settings.MEDIA_ROOT/media/MJUPLEX1.png', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='dept',
            field=models.CharField(choices=[('mju', 'MJU'), ('uplex', 'UPLEX'), ('not-specified', 'Not Specified')], max_length=100, null=True),
        ),
    ]
